name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - run: npm install
      - run: npm run test
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
<<<<<<< HEAD:.github/workflows/release.yaml
=======
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run release
>>>>>>> d39142d6796c4089ef73f59a92cd4fdfd6d42942:.github/workflows/build-test-release.yaml
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run release
